version: '3.8'
services:
    app:
        container_name: app
        restart: always
        build: .
        ports:
            - 3000:4000
        environment:
            - DB_HOST=${DB_USER}
        depends_on:
            - postgres
        volumes:
            - .:/usr/src/app
        command: bash -c "npm run migration:up && npm run start:prod"
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - '5433:5432'
        volumes:
            - data:/data/db
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}

volumes:
    data: {}
